version: '3.3'

services:
  php:
      build:
        context: .
        dockerfile: dockerfile
      container_name: php8poke
      depends_on:
      - dbBB
      image: php:8.0-apache
      volumes:
      - ./php:/var/www/html/
      ports:
      - 80:80
  dbBB:
      container_name: mysql8poke
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      environment: 
        MYSQL_ROOT_PASSWORD: sdfjqgsfhg987
        MYSQL_DATABASE: Pokemon
        MYSQL_USER: BeWeb
        MYSQL_PASSWORD: Pokemon34
      ports:
      - 3306:3306
  phpmya:
      image: phpmyadmin/phpmyadmin:latest
      container_name: pmapoke
      environment:
        PMA_ARBITRARY: 1
        PMA_HOST: dbBB
        PMA_USER: BeWeb
        PMA_PASSWORD: Pokemon34
        UPLOAD_LIMIT: 320M
      ports:
      - 8899:80